apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd

spec:
  project: default

  destination:
    namespace: longhorn-system
    server: https://kubernetes.default.svc

  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.9.1

    helm:
      valueFiles:
        - values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true