apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces/application.yaml
  - longhorn/application.yaml
  - cert-manager/application.yaml
  - monitoring/application.yaml
  - percona/application.yaml
  - ../applications/mysql/application.yaml